name: Release

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_NAME: "modern-cpp-template"
  BUILD_TYPE: Release

jobs:
  build:
    name: {% raw %}${{ matrix.config.name }}{% endraw %}
    runs-on: {% raw %}${{ matrix.config.os }}{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            artifact_ext: '.zip',
            os: windows-latest,
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
          }
        - {
            name: "Ubuntu Latest GCC",
            artifact_ext: '.tar.gz',
            os: ubuntu-latest,
            cc: "gcc",
            cxx: "g++",
          }
        - {
            name: "macOS Latest Clang",
            artifact_ext: '.tar.gz',
            os: macos-latest,
            cc: "clang",
            cxx: "clang++",
          }

    steps:
    - name: set version name (Windows)
      id: version_win
      if: {% raw %}${{ runner.os == 'Windows' }}{% endraw %}
      run: |
        $TAG = ({% raw %}${env:GITHUB_REF}{% endraw %} -replace 'refs/tags/', '')
        echo "::set-output name=name::$TAG"
    
    - name: set version name
      id: version
      if: {% raw %}${{ runner.os != 'Windows' }}{% endraw %}
      run: echo ::set-output name=name::{% raw %}${GITHUB_REF#refs/tags/}{% endraw %}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: {% raw %}${{ github.HOME }}{% endraw %}/.local
        key: {% raw %}${{ runner.os }}{% endraw %}-dependencies

    - name: install GoogleTest
      if: {% raw %}${{ steps.cache.output.cache-hit != 'true' }}{% endraw %}
      run: |
        cd ..
        git clone https://github.com/google/googletest.git --branch release-1.10.0
        cd googletest
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX="$HOME/.local" -Dgtest_force_shared_crt=1
        cmake --build build --config Release
        cmake --build build --target install --config Release
        cd ../modern-cpp-template

    - name: configure
      run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX="$HOME/.local"
      
    - name: build
      run: cmake --build build --config "$env:BUILD_TYPE" -j4

    - name: run tests
      run: |
        cd build
        ctest -C "$env:BUILD_TYPE" -VV

    # for a release not containing directly the source code, replace the files archived
    # with the actual files needed (i.e. *.lib/*.a and *.h(pp))

    - name: generate archive (Windows)
      if: {% raw %}${{ runner.os == 'Windows' }}{% endraw %}
      run: |
        rmdir -r -fo build
        7z a -tzip $HOME/artifact.zip *


    - name: generate archive
      if: {% raw %}${{ runner.os != 'Windows' }}{% endraw %}
      run: |
        rm -rf build
        tar -cvzf $HOME/artifact.tar.gz .

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      if: {% raw %}${{ runner.os == 'Windows' }}{% endraw %}
      with:
        name: {% raw %}${{ runner.os }}{% endraw %}-{% raw %}${{ steps.version_win.outputs.name }}{% endraw %}
        path: '~/artifact.*'

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      if: {% raw %}${{ runner.os != 'Windows' }}{% endraw %}
      with:
        name: {% raw %}${{ runner.os }}{% endraw %}-{% raw %}${{ steps.version.outputs.name }}{% endraw %}
        path: '~/artifact.*'

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: set version name
      id: version
      run: echo ::set-output name=name::{% raw %}${GITHUB_REF#refs/tags/}{% endraw %}

    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: {% raw %}${{ github.ref }}{% endraw %}
        release_name: Release {% raw %}${{ steps.version.outputs.name }}{% endraw %}
        # if needed, you can set the release body here
        #body: "Release notes"
        draft: false
        prerelease: false

    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: "Linux-{% raw %}${{ steps.version.outputs.name }}{% endraw %}"
        path: ./

    - name: upload ubuntu release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
      with:
        upload_url: {% raw %}${{ steps.create_release.outputs.upload_url }}{% endraw %}
        asset_path: "artifact.tar.gz"
        asset_name: "{% raw %}${{ env.PROJECT_NAME }}{% endraw %}-Linux-{% raw %}${{ steps.version.outputs.name }}{% endraw %}.tar.gz"
        asset_content_type: application/x-tar

    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: "Windows-{% raw %}${{ steps.version.outputs.name }}{% endraw %}"
        path: ./

    - name: upload windows release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
      with:
        upload_url: {% raw %}${{ steps.create_release.outputs.upload_url }}{% endraw %}
        asset_path: "artifact.zip"
        asset_name: "{% raw %}${{ env.PROJECT_NAME }}{% endraw %}-Windows-{% raw %}${{ steps.version.outputs.name }}{% endraw %}.zip"
        asset_content_type: application/zip

    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: "macOS-{% raw %}${{ steps.version.outputs.name }}{% endraw %}"
        path: ./

    - name: upload macos release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
      with:
        upload_url: {% raw %}${{ steps.create_release.outputs.upload_url }}{% endraw %}
        asset_path: "./artifact.tar.gz"
        asset_name: "{% raw %}${{ env.PROJECT_NAME }}{% endraw %}-macOS-{% raw %}${{ steps.version.outputs.name }}{% endraw %}.tar.gz"
        asset_content_type: application/x-tar
